name: GitHub Metrics

on:
  schedule: [{ cron: "0 0 * * *" }] # Updates daily
  push: { branches: ["main"] }
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: donaldlwandle
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Africa/Johannesburg
